version: '3'

services:
  reporting_system:
    build:
      context: ./reporting_system/build
    ports:
      - "8080:8080"
    depends_on:
      - db
      - opc_service
    environment:
      OPC_SERVICE_HOST: hostname
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/reporting_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  opc_service:
    hostname: hostname
    build:
      context: ./opc_service/target
    ports:
      - "8081:8081"
  db:
    image: 'postgres:14-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reporting_system
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: