--liquibase formatted sql

--changeset alina.parfenteva:1
SET search_path TO calculations;

--changeset alina.parfenteva:2
INSERT INTO tag (permanent_name, address, description, initial, calc_method)
VALUES ('accAct_acceptanceActNumber', 'WinCC_OA.acts.' || 'accAct_acceptanceActNumber', 
        'Номер акта приема-сдачи нефти', 
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_acceptanceActDate', 'WinCC_OA.acts.' || 'accAct_acceptanceActDate', 
        'Дата акта приема-сдачи нефти', 
        TRUE,'ACCEPTANCE_ACT'),
       ('accAct_oilAcceptancePoint', 'WinCC_OA.acts.' || 'accAct_oilAcceptancePoint', 
        'Пункт приема-сдачи нефти', 
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_pointOwner', 'WinCC_OA.acts.' || 'accAct_pointOwner', 
        'Предприятие (владелец) ПСП', 
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_SIKN', 'WinCC_OA.acts.' || 'accAct_SIKN', 
        'СИКН', TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_deliverOrg', 'WinCC_OA.acts.' || 'accAct_deliverOrg', 
        'Организация сдающей стороны', 
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_deliverNameTitle', 'WinCC_OA.acts.' || 'accAct_deliverNameTitle', 
        'Фамилия И.О. представителя сдающей стороны', 
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_deliverProxyDate', 'WinCC_OA.acts.' || 'accAct_deliverProxyDate',
        'Дата доверенности сдающей стороны',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_deliverProxyNumber', 'WinCC_OA.acts.' || 'accAct_deliverProxyNumber', 'Номер доверенности сдающей стороны',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_receiverOrg', 'WinCC_OA.acts.' || 'accAct_receiverOrg',
        'Организация принимающей стороны',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_receiverNameTitle', 'WinCC_OA.acts.' || 'accAct_receiverNameTitle',
        'Фамилия И.О. представителя принимающей стороны',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_receiverProxyDate', 'WinCC_OA.acts.' || 'accAct_receiverProxyDate',
        'Дата доверенности принимающей стороны',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_receiverProxyNumber', 'WinCC_OA.acts.' || 'accAct_receiverProxyNumber',
        'Номер доверенности принимающей стороны',
        TRUE, 'ACCEPTANCE_ACT'),

    -- показатели нефти
       ('accAct_dtStart_shiftn', 'WinCC_OA.acts.' || 'accAct_dtStart_shiftn',
        'Дата и время начала смены n. Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_dtStart_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_dtEnd_shiftn', 'WinCC_OA.acts.' || 'accAct_dtEnd_shiftn',
        'Дата и время окончания смены n. Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_dtEnd_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_prevEndVol_shiftn', 'WinCC_OA.acts.' || 'accAct_prevEndVol_shiftn',
        'Результаты измерений СИКН: объем на время окончания предыдущей сдачи (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_prevEndVol_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_prevEndMass_shiftn', 'WinCC_OA.acts.' || 'accAct_prevEndMass_shiftn',
        'Результаты измерений СИКН: масса на время окончания предыдущей сдачи (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_prevEndMass_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_currentEndVol_shiftn', 'WinCC_OA.acts.' || 'accAct_currentEndVol_shiftn',
        'Результаты измерений СИКН: объем на момент завершения текущей сдачи (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_currentEndVol_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_currentEndMass_shiftn', 'WinCC_OA.acts.' || 'accAct_currentEndMass_shiftn',
        'Результаты измерений СИКН: масса на момент завершения текущей сдачи (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_currentEndMass_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_grossOilVol_shiftn', 'WinCC_OA.acts.' || 'accAct_grossOilVol_shiftn',
        'Масса нефти брутто: объем (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_grossOilVol_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_grossOilMass_shiftn', 'WinCC_OA.acts.' || 'accAct_grossOilMass_shiftn',
        'Масса нефти брутто: масса (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_grossOilMass_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_oilTemp_shiftn', 'WinCC_OA.acts.' || 'accAct_oilTemp_shiftn',
        'Температура нефти при условиях измерений объема (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_oilTemp_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_oilPressure_shiftn', 'WinCC_OA.acts.' || 'accAct_oilPressure_shiftn',
        'Давление нефти при условиях измерений объема (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_oilPressure_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_oilDensity_shiftn', 'WinCC_OA.acts.' || 'accAct_oilDensity_shiftn',
        'Плотность нефти при температуре и давлении при условиях измерениц объема (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_oilDensity_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_correctionForDensity_shiftn', 'WinCC_OA.acts.' || 'accAct_correctionForDensity_shiftn',
        'Поправка на плотность (смена n). Заполняется при отказе поточного преобразователя плотности. Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_correctionForDensity_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_oilPassportNumber_shiftn', 'WinCC_OA.acts.' || 'accAct_oilPassportNumber_shiftn',
        '№ паспорта качества нефти (смена n). Заполняется при отказе поточного преобразователя плотности. Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_oilPassportNumber_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_massFractionBallast_shiftn', 'WinCC_OA.acts.' || 'accAct_massFractionBallast_shiftn',
        'Массовая доля балласта всего (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_massFractionBallast_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_massFractionWater_shiftn', 'WinCC_OA.acts.' || 'accAct_massFractionWater_shiftn',
        'Массовая доля воды (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_massFractionWater_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_massFractionChlorideSalt_shiftn', 'WinCC_OA.acts.' || 'accAct_massFractionChlorideSalt_shiftn',
        'Массовая доля хлористых солей (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_massFractionChlorideSalt_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_massFractionAdmixture_shiftn', 'WinCC_OA.acts.' || 'accAct_massFractionAdmixture_shiftn',
        'Массовая доля механических примесей (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_massFractionAdmixture_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_massFractionSulfur_shiftn', 'WinCC_OA.acts.' || 'accAct_massFractionSulfur_shiftn',
        'Массовая доля серы (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_massFractionSulfur_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_concentrationChlorideSalt_shiftn', 'WinCC_OA.acts.' || 'accAct_concentrationChlorideSalt_shiftn',
        'Концентрация хлористых солей (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_concentrationChlorideSalt_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_ballastMass_shiftn', 'WinCC_OA.acts.' || 'accAct_ballastMass_shiftn',
        'Масса балласта (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_ballastMass_shift1',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_oilNetMass_shiftn', 'WinCC_OA.acts.' || 'accAct_oilNetMass_shiftn',
        'Масса нефти нетто (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет WinCC_OA.acts.accAct_oilNetMass_shift1',
        TRUE, 'ACCEPTANCE_ACT'),

    -- нижняя часть акта
       ('accAct_oilNetMassInWords', 'WinCC_OA.acts.' || 'accAct_oilNetMassInWords',
        'Масса нефти нетто (прописью)',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_GOST', 'WinCC_OA.acts.' || 'accAct_GOST',
        'Обозначение нефти по ГОСТ Р 51858-2002',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_deliverNameFooter', 'WinCC_OA.acts.' || 'accAct_deliverNameFooter',
        'И.О. Фамилия представителя сдающей стороны',
        TRUE, 'ACCEPTANCE_ACT'),
       ('accAct_receiverNameFooter', 'WinCC_OA.acts.' || 'accAct_receiverNameFooter',
        'И.О. Фамилия представителя сдающей стороны',
        TRUE, 'ACCEPTANCE_ACT');