--liquibase formatted sql

--changeset alina.parfenteva:1
SET search_path TO manual_reports;

--changeset alina.parfenteva:2
-- Входные данные
INSERT INTO tag (permanent_name, address, description, initial, report_type)
VALUES ('protocolNumber', 'kmhMoistMet.' || 'protocolNumber',
        'Номер протокола',
        TRUE, 'KMH_MOISTURE_METER'),
       ('siknNumber', 'kmhMoistMet.' || 'siknNumber',
        'СИКН №',
        TRUE, 'KMH_MOISTURE_METER'),
       ('place_name', 'kmhMoistMet.' || 'place_name',
        'Место проведения КМХ',
        TRUE, 'KMH_MOISTURE_METER'),

       -- Таблица 1
       ('reserve_mm_type', 'kmhMoistMet.' || 'reserve_mm_type',
        'Тип, марка резервного влагомера',
        TRUE, 'KMH_MOISTURE_METER'),
       ('working_mm_type', 'kmhMoistMet.' || 'working_mm_type',
        'Тип, марка рабочего влагомера', TRUE, 'KMH_MOISTURE_METER'),
       ('reserve_mm_number', 'kmhMoistMet.' || 'reserve_mm_number',
        'Заводской номер резервного влагомера',
        TRUE, 'KMH_MOISTURE_METER'),
       ('working_mm_number', 'kmhMoistMet.' || 'working_mm_number',
        'Заводской номер рабочего влагомера',
        TRUE, 'KMH_MOISTURE_METER'),
       ('reserve_mm_date', 'kmhMoistMet.' || 'reserve_mm_date',
        'Дата последней поверки резервного влагомера',
        TRUE, 'KMH_MOISTURE_METER'),
       ('working_mm_date', 'kmhMoistMet.' || 'working_mm_date', 'Дата последней поверки рабочего влагомера',
        TRUE, 'KMH_MOISTURE_METER'),
       ('reserve_mm_delta_W_kv', 'kmhMoistMet.' || 'reserve_mm_delta_W_kv',
        'Предел абсолютной погрешности измерений массовой доли воды в нефти резервным влагомером, ΔWкв %',
        TRUE, 'KMH_MOISTURE_METER'),
       ('working_mm_delta_W_kv', 'kmhMoistMet.' || 'working_mm_delta_W_kv',
        'Предел абсолютной погрешности измерений массовой доли воды в нефти рабочим влагомером, ΔWкв %',
        TRUE, 'KMH_MOISTURE_METER'),
       ('reserve_mm_delta_W_0', 'kmhMoistMet.' || 'reserve_mm_delta_W_0',
        'Предел допускаемой абсолютной погрешности определения доли воды в ХАЛ резервным влагомером по ГОСТ 2477, ΔW0 %',
        TRUE, 'KMH_MOISTURE_METER'),
       ('working_mm_delta_W_0', 'kmhMoistMet.' || 'working_mm_delta_W_0',
        'Предел допускаемой абсолютной погрешности определения доли воды в ХАЛ рабочим влагомером по ГОСТ 2477, ΔW0 %',
        TRUE, 'KMH_MOISTURE_METER'),

       -- Таблица 2
       ('measure_time', 'kmhMoistMet.' || 'measure_time',
        'Время проведения замеров (московское)',
        TRUE, 'KMH_MOISTURE_METER'),
       ('work_mm_phi_v', 'kmhMoistMet.' || 'work_mm_phi_v',
        'Значение влагосодержания φв по рабочему влагомеру,  (% объемных)',
        TRUE, 'KMH_MOISTURE_METER'),
       ('reserve_mm_phi_v', 'kmhMoistMet.' || 'reserve_mm_phi_v',
        'Значение влагосодержания φв по резервному влагомеру,  (% объемных)',
        TRUE, 'KMH_MOISTURE_METER'),
       ('work_mm_W_kv', 'kmhMoistMet.' || 'work_mm_W_kv',
        'Значение влагосодержания Wкв по рабочему влагомеру, (% массовых)',
        TRUE, 'KMH_MOISTURE_METER'),
       ('reserve_mm_W_kv', 'kmhMoistMet.' || 'reserve_mm_W_kv',
        'Значение влагосодержания Wкв по резервному влагомеру, (% массовых)',
        TRUE, 'KMH_MOISTURE_METER'),
       ('W_0', 'kmhMoistMet.' || 'W_0',
        'Значение влагосодержания W0, по анализам ХАЛ, (% массовых)',
        TRUE, 'KMH_MOISTURE_METER'),
       ('rho_v', 'kmhMoistMet.' || 'rho_v',
        'Плотность нефти по СИКН, ρv, кг/м3',
        TRUE, 'KMH_MOISTURE_METER'),

       -- Нижняя часть
       ('deliverOrg', 'kmhMoistMet.' || 'deliverOrg',
        'Организация сдающей стороны',
        TRUE, 'KMH_MOISTURE_METER'),
       ('metrologistName', 'kmhMoistMet.' || 'metrologistName',
        'Фамилия И.О. инженера-метролога сдающей стороны',
        TRUE, 'KMH_MOISTURE_METER'),
       ('chemistName', 'kmhMoistMet.' || 'chemistName',
        'Фамилия И.О. инженера-химика сдающей стороны',
        TRUE, 'KMH_MOISTURE_METER'),
       ('receiverOrg', 'kmhMoistMet.' || 'receiverOrg',
        'Организация принимающей стороны',
        TRUE, 'KMH_MOISTURE_METER'),
       ('receiverPosition', 'kmhMoistMet.' || 'receiverPosition',
        'Должность лица от принимающей стороны',
        TRUE, 'KMH_MOISTURE_METER'),
       ('receiverName', 'kmhMoistMet.' || 'receiverName',
        'Фамилия И.О. лица от сдающей стороны',
        TRUE, 'KMH_MOISTURE_METER'),
       ('serviceOrg', 'kmhMoistMet.' || 'serviceOrg',
        'Название сервисной организации',
        TRUE, 'KMH_MOISTURE_METER'),
       ('servicePosition', 'kmhMoistMet.' || 'servicePosition',
        'Должность лица от сервисной организации',
        TRUE, 'KMH_MOISTURE_METER'),
       ('serviceName', 'kmhMoistMet.' || 'serviceName',
        'Фамилия И.О. лица от сервисной организации',
        TRUE, 'KMH_MOISTURE_METER');

-- выходные данные
INSERT INTO tag (permanent_name, address, description, initial, report_type)
VALUES ('work_mm_W_id', 'kmhMoistMet.' || 'work_mm_W_id',
        'Расхождение результатов измерений для рабочего влагомера Ŵid =|Wкв –W0|, (%)',
        FALSE, 'KMH_MOISTURE_METER'),
       ('reserve_mm_W_id', 'kmhMoistMet.' || 'reserve_mm_W_id',
        'Расхождение результатов измерений для резервного влагомера Ŵid =|Wкв –W0|, (%)',
        FALSE, 'KMH_MOISTURE_METER'),
       ('working_mm_conclusion', 'kmhMoistMet.' || 'working_mm_conclusion',
        'годен/не годен для рабочего влагомера',
        FALSE, 'KMH_MOISTURE_METER'),
       ('reserve_mm_conclusion', 'kmhMoistMet.' || 'reserve_mm_conclusion',
        'годен/не годен для резервного влагомера',
        FALSE, 'KMH_MOISTURE_METER');