--liquibase formatted sql

--changeset alina.parfenteva:1
SET search_path TO manual_reports;

--changeset alina.parfenteva:2
-- Входные данные
INSERT INTO tag (permanent_name, address, description, initial, report_type)
VALUES ('workingOrReserve', 'kmhDensMet.' || 'workingOrReserve',
        'КМХ по рабочему или резервному ПП. Может иметь только 2 значения: "рабочий" или "резервный"',
        TRUE, 'KMH_DENSITY_METER'),
       ('protocolNumber', 'kmhDensMet.' || 'protocolNumber',
        'Номер протокола',
        TRUE, 'KMH_DENSITY_METER'),
       ('siknNumber', 'kmhDensMet.' || 'siknNumber',
        'СИКН №',
        TRUE, 'KMH_DENSITY_METER'),
       ('place_name', 'kmhDensMet.' || 'place_name',
        'Место проведения КМХ',
        TRUE, 'KMH_DENSITY_METER'),

       -- Таблица 1
       ('pp_type', 'kmhDensMet.' || 'pp_type',
        'Тип, марка ПП',
        TRUE, 'KMH_DENSITY_METER'),
       ('areometer_type', 'kmhDensMet.' || 'areometer_type',
        'Тип, марка ареометра', TRUE, 'KMH_DENSITY_METER'),
       ('pp_number', 'kmhDensMet.' || 'pp_number',
        'Заводской номер ПП',
        TRUE, 'KMH_DENSITY_METER'),
       ('areometer_number', 'kmhDensMet.' || 'areometer_number',
        'Заводской номер ареометра',
        TRUE, 'KMH_DENSITY_METER'),
       ('pp_date', 'kmhDensMet.' || 'pp_date',
        'Дата последней поверки ПП',
        TRUE, 'KMH_DENSITY_METER'),
       ('areometer_date', 'kmhDensMet.' || 'areometer_date', 'Дата последней поверки ареометра',
        TRUE, 'KMH_DENSITY_METER'),
       ('delta_pp', 'kmhDensMet.' || 'delta_pp',
        'Предел допускаемой абсолютной погрешности ПП (Δ, кг/м3 )',
        TRUE, 'KMH_DENSITY_METER'),
       ('delta_areometer', 'kmhDensMet.' || 'delta_areometer',
        'Предел допускаемой абсолютной погрешности ареометра (Δ, кг/м3 )',
        TRUE, 'KMH_DENSITY_METER'),
       ('delta_syst', 'kmhDensMet.' || 'delta_syst',
        'Систематическая  погрешность метода определения плотности нефти ареометром (обязательно со знаком «+» или «-»)  -  из  свидетельства о метрологической аттестации МВИ плотности на данную СИКН, (Δ сист , кг/м3 )',
        TRUE, 'KMH_DENSITY_METER'),
       ('delta_met', 'kmhDensMet.' || 'delta_met',
        'Погрешность метода определения плотности нефти ареометром (без знака) -  из  свидетельства о метрологической аттестации МВИ плотности на данную СИКН, (Δ мет , кг/м3)',
        TRUE, 'KMH_DENSITY_METER'),

       -- Таблица 2
       ('Q_i', 'kmhDensMet.' || 'Q_i',
        '',
        TRUE, 'KMH_DENSITY_METER'),
       ('t_pl_i', 'kmhDensMet.' || 't_pl_i',
        '',
        TRUE, 'KMH_DENSITY_METER'),
       ('P_pl_i', 'kmhDensMet.' || 'P_pl_i',
        '',
        TRUE, 'KMH_DENSITY_METER'),
       ('rho_pl_i', 'kmhDensMet.' || 'rho_pl_i',
        '',
        TRUE, 'KMH_DENSITY_METER'),
       ('rho_meas_i', 'kmhDensMet.' || 'rho_meas_i',
        '',
        TRUE, 'KMH_DENSITY_METER'),
       ('t_ar_i', 'kmhDensMet.' || 't_ar_i',
        '',
        TRUE, 'KMH_DENSITY_METER'),

       -- Нижняя часть
       ('deliverOrg', 'kmhDensMet.' || 'deliverOrg',
        'Организация сдающей стороны',
        TRUE, 'KMH_DENSITY_METER'),
       ('metrologistName', 'kmhDensMet.' || 'metrologistName',
        'Фамилия И.О. инженера-метролога сдающей стороны',
        TRUE, 'KMH_DENSITY_METER'),
       ('chemistName', 'kmhDensMet.' || 'chemistName',
        'Фамилия И.О. инженера-химика сдающей стороны',
        TRUE, 'KMH_DENSITY_METER'),
       ('receiverOrg', 'kmhDensMet.' || 'receiverOrg',
        'Организация принимающей стороны',
        TRUE, 'KMH_DENSITY_METER'),
       ('receiverPosition', 'kmhDensMet.' || 'receiverPosition',
        'Должность лица от принимающей стороны',
        TRUE, 'KMH_DENSITY_METER'),
       ('receiverName', 'kmhDensMet.' || 'receiverName',
        'Фамилия И.О. лица от принимающей стороны',
        TRUE, 'KMH_DENSITY_METER'),
       ('serviceOrg', 'kmhDensMet.' || 'serviceOrg',
        'Название сервисной организации',
        TRUE, 'KMH_DENSITY_METER'),
       ('servicePosition', 'kmhDensMet.' || 'servicePosition',
        'Должность лица от сервисной организации',
        TRUE, 'KMH_DENSITY_METER'),
       ('serviceName', 'kmhDensMet.' || 'serviceName',
        'Фамилия И.О. лица от сервисной организации',
        TRUE, 'KMH_DENSITY_METER');

-- выходные данные
INSERT INTO tag (permanent_name, address, description, initial, report_type)
VALUES ('beta15', 'kmhDensMet.' || 'beta15',
        '',
        FALSE, 'KMH_DENSITY_METER'),
       ('gamma_pl_i', 'kmhDensMet.' || 'gamma_pl_i',
        '',
        FALSE, 'KMH_DENSITY_METER'),
       ('rho_lpr_i', 'kmhDensMet.' || 'rho_lpr_i',
        '',
        FALSE, 'KMH_DENSITY_METER'),
       ('delta_pk_i', 'kmhDensMet.' || 'delta_pk_i',
        '',
        FALSE, 'KMH_DENSITY_METER'),
       ('conclusion', 'kmhDensMet.' || 'conclusion',
        'годен/не годен',
        FALSE, 'KMH_DENSITY_METER');