--liquibase formatted sql

--changeset alina.parfenteva:1
SET search_path TO manual_reports;

--changeset alina.parfenteva:2
INSERT INTO report_type (id, name, description, active)
VALUES ('acceptanceAct', 'Акт приема-сдачи нефти', 'Для валовых объемов нефти', TRUE);

INSERT INTO tag (permanent_name, address, description, initial, report_type_id)
VALUES ('acceptanceActNumber', 'accAct.' || 'acceptanceActNumber', 
        'Номер акта приема-сдачи нефти', 
        TRUE, 'acceptanceAct'),
       ('acceptanceActDate', 'accAct.' || 'acceptanceActDate', 
        'Дата акта приема-сдачи нефти', 
        TRUE,'acceptanceAct'),
       ('oilAcceptancePoint', 'accAct.' || 'oilAcceptancePoint', 
        'Пункт приема-сдачи нефти', 
        TRUE, 'acceptanceAct'),
       ('pointOwner', 'accAct.' || 'pointOwner', 
        'Предприятие (владелец) ПСП', 
        TRUE, 'acceptanceAct'),
       ('SIKN', 'accAct.' || 'SIKN', 
        'СИКН', TRUE, 'acceptanceAct'),
       ('deliverOrg', 'accAct.' || 'deliverOrg', 
        'Организация сдающей стороны', 
        TRUE, 'acceptanceAct'),
       ('deliverNameTitle', 'accAct.' || 'deliverNameTitle', 
        'Фамилия И.О. представителя сдающей стороны', 
        TRUE, 'acceptanceAct'),
       ('deliverProxyDate', 'accAct.' || 'deliverProxyDate',
        'Дата доверенности сдающей стороны',
        TRUE, 'acceptanceAct'),
       ('deliverProxyNumber', 'accAct.' || 'deliverProxyNumber', 'Номер доверенности сдающей стороны',
        TRUE, 'acceptanceAct'),
       ('receiverOrg', 'accAct.' || 'receiverOrg',
        'Организация принимающей стороны',
        TRUE, 'acceptanceAct'),
       ('receiverNameTitle', 'accAct.' || 'receiverNameTitle',
        'Фамилия И.О. представителя принимающей стороны',
        TRUE, 'acceptanceAct'),
       ('receiverProxyDate', 'accAct.' || 'receiverProxyDate',
        'Дата доверенности принимающей стороны',
        TRUE, 'acceptanceAct'),
       ('receiverProxyNumber', 'accAct.' || 'receiverProxyNumber',
        'Номер доверенности принимающей стороны',
        TRUE, 'acceptanceAct'),

    -- показатели нефти
       ('dtStart_shiftn', 'accAct.' || 'dtStart_shiftn',
        'Дата и время начала смены n. Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.dtStart_shift1',
        TRUE, 'acceptanceAct'),
       ('dtEnd_shiftn', 'accAct.' || 'dtEnd_shiftn',
        'Дата и время окончания смены n. Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.dtEnd_shift1',
        TRUE, 'acceptanceAct'),
       ('prevEndVol_shiftn', 'accAct.' || 'prevEndVol_shiftn',
        'Результаты измерений СИКН: объем на время окончания предыдущей сдачи (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.prevEndVol_shift1',
        TRUE, 'acceptanceAct'),
       ('prevEndMass_shiftn', 'accAct.' || 'prevEndMass_shiftn',
        'Результаты измерений СИКН: масса на время окончания предыдущей сдачи (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.prevEndMass_shift1',
        TRUE, 'acceptanceAct'),
       ('currentEndVol_shiftn', 'accAct.' || 'currentEndVol_shiftn',
        'Результаты измерений СИКН: объем на момент завершения текущей сдачи (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.currentEndVol_shift1',
        TRUE, 'acceptanceAct'),
       ('currentEndMass_shiftn', 'accAct.' || 'currentEndMass_shiftn',
        'Результаты измерений СИКН: масса на момент завершения текущей сдачи (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.currentEndMass_shift1',
        TRUE, 'acceptanceAct'),
       ('grossOilVol_shiftn', 'accAct.' || 'grossOilVol_shiftn',
        'Масса нефти брутто: объем (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.grossOilVol_shift1',
        TRUE, 'acceptanceAct'),
       ('grossOilMass_shiftn', 'accAct.' || 'grossOilMass_shiftn',
        'Масса нефти брутто: масса (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.grossOilMass_shift1',
        TRUE, 'acceptanceAct'),
       ('oilTemp_shiftn', 'accAct.' || 'oilTemp_shiftn',
        'Температура нефти при условиях измерений объема (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.oilTemp_shift1',
        TRUE, 'acceptanceAct'),
       ('oilPressure_shiftn', 'accAct.' || 'oilPressure_shiftn',
        'Давление нефти при условиях измерений объема (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.oilPressure_shift1',
        TRUE, 'acceptanceAct'),
       ('oilDensity_shiftn', 'accAct.' || 'oilDensity_shiftn',
        'Плотность нефти при температуре и давлении при условиях измерениц объема (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.oilDensity_shift1',
        TRUE, 'acceptanceAct'),
       ('correctionForDensity_shiftn', 'accAct.' || 'correctionForDensity_shiftn',
        'Поправка на плотность (смена n). Заполняется при отказе поточного преобразователя плотности. Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.correctionForDensity_shift1',
        TRUE, 'acceptanceAct'),
       ('oilPassportNumber_shiftn', 'accAct.' || 'oilPassportNumber_shiftn',
        '№ паспорта качества нефти (смена n). Заполняется при отказе поточного преобразователя плотности. Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.oilPassportNumber_shift1',
        TRUE, 'acceptanceAct'),
       ('massFractionBallast_shiftn', 'accAct.' || 'massFractionBallast_shiftn',
        'Массовая доля балласта всего (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.massFractionBallast_shift1',
        TRUE, 'acceptanceAct'),
       ('massFractionWater_shiftn', 'accAct.' || 'massFractionWater_shiftn',
        'Массовая доля воды (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.massFractionWater_shift1',
        TRUE, 'acceptanceAct'),
       ('massFractionChlorideSalt_shiftn', 'accAct.' || 'massFractionChlorideSalt_shiftn',
        'Массовая доля хлористых солей (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.massFractionChlorideSalt_shift1',
        TRUE, 'acceptanceAct'),
       ('massFractionAdmixture_shiftn', 'accAct.' || 'massFractionAdmixture_shiftn',
        'Массовая доля механических примесей (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.massFractionAdmixture_shift1',
        TRUE, 'acceptanceAct'),
       ('massFractionSulfur_shiftn', 'accAct.' || 'massFractionSulfur_shiftn',
        'Массовая доля серы (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.massFractionSulfur_shift1',
        TRUE, 'acceptanceAct'),
       ('concentrationChlorideSalt_shiftn', 'accAct.' || 'concentrationChlorideSalt_shiftn',
        'Концентрация хлористых солей (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.concentrationChlorideSalt_shift1',
        TRUE, 'acceptanceAct'),
       ('ballastMass_shiftn', 'accAct.' || 'ballastMass_shiftn',
        'Масса балласта (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.ballastMass_shift1',
        TRUE, 'acceptanceAct'),
       ('oilNetMass_shiftn', 'accAct.' || 'oilNetMass_shiftn',
        'Масса нефти нетто (смена n). Вместо n будет подставлен номер смены. Например, адрес тега для первой смены будет accAct.oilNetMass_shift1',
        TRUE, 'acceptanceAct'),

    -- нижняя часть акта
       ('oilNetMassInWords', 'accAct.' || 'oilNetMassInWords',
        'Масса нефти нетто (прописью)',
        TRUE, 'acceptanceAct'),
       ('GOST', 'accAct.' || 'GOST',
        'Обозначение нефти по ГОСТ Р 51858-2002',
        TRUE, 'acceptanceAct'),
       ('deliverNameFooter', 'accAct.' || 'deliverNameFooter',
        'И.О. Фамилия представителя сдающей стороны',
        TRUE, 'acceptanceAct'),
       ('receiverNameFooter', 'accAct.' || 'receiverNameFooter',
        'И.О. Фамилия представителя сдающей стороны',
        TRUE, 'acceptanceAct');