--liquibase formatted sql

--changeset alina.parfenteva:1
SET search_path TO manual_reports;

--changeset alina.parfenteva:2
-- Входные данные
INSERT INTO tag (permanent_name, address, description, initial, report_type)
VALUES ('deliver_org', 'kmhMassmByPu.' || 'deliver_org',
        'Наименование организации сдаюей стороны',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('siknNumber', 'kmhMassmByPu.' || 'siknNumber',
        'СИКН №',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('protocolNumber', 'kmhMassmByPu.' || 'protocolNumber',
        'Номер протокола',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('il_number_title', 'kmhMassmByPu.' || 'il_number_title',
        'ИЛ № (в заголовке)',
        TRUE, 'KMH_MASSM_BY_PU'),

       ('massmeterModel', 'kmhMassmByPu.massmeterModel', 'модель массомера, предъявленного для контроля', TRUE,
        'KMH_MASSM_BY_PU'),
       ('place_name', 'kmhMassmByPu.place_name', 'место проведения контроля МХ - наименование объекта (ПСП)', TRUE,
        'KMH_MASSM_BY_PU'),
       ('place_owner', 'kmhMassmByPu.place_owner',
        'место проведения контроля МХ - наименование владельца объекта (ПСП)', TRUE, 'KMH_MASSM_BY_PU'),
       ('massmeterSensor', 'kmhMassmByPu.massmeterSensor', 'модель сенсора массомера', TRUE, 'KMH_MASSM_BY_PU'),
       ('massmeterDu', 'kmhMassmByPu.massmeterDu', 'Ду массомера', TRUE, 'KMH_MASSM_BY_PU'),
       ('massmeterNumber', 'kmhMassmByPu.massmeterNumber', 'заводской номер массомера', TRUE, 'KMH_MASSM_BY_PU'),
       ('pepModel', 'kmhMassmByPu.pepModel', 'модель ПЭП', TRUE, 'KMH_MASSM_BY_PU'),
       ('pepNumber', 'kmhMassmByPu.pepNumber', 'заводской номер ПЭП', TRUE, 'KMH_MASSM_BY_PU'),
       ('installedOn', 'kmhMassmByPu.installedOn', 'установлен на (СИКН, СИКНП, СИКЖУ, СИКНС)', TRUE,
        'KMH_MASSM_BY_PU'),
       ('ilNumber', 'kmhMassmByPu.' || 'ilNumber',
        'Номер измерительной линии',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('operatingFluid', 'kmhMassmByPu.' || 'operatingFluid',
        'Рабочая жидкость',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('cpType', 'kmhMassmByPu.cpType', 'тип компакт-прувера', TRUE, 'KMH_MASSM_BY_PU'),
       ('cpGrade', 'kmhMassmByPu.cpGrade', 'разряд компакт-прувера', TRUE, 'KMH_MASSM_BY_PU'),
       ('cpNumber', 'kmhMassmByPu.cpNumber', 'заводской номер компакт-прувера', TRUE, 'KMH_MASSM_BY_PU'),
       ('cpDate', 'kmhMassmByPu.cpDate', 'дата поверки компакт-прувера', TRUE, 'KMH_MASSM_BY_PU'),
       ('tprType', 'kmhMassmByPu.tprType', 'тип ТПР', TRUE, 'KMH_MASSM_BY_PU'),
       ('tprRange', 'kmhMassmByPu.tprRange', 'диапазон измерений ТПР', TRUE, 'KMH_MASSM_BY_PU'),
       ('tprNumber', 'kmhMassmByPu.tprNumber', 'заводской номер ТПР', TRUE, 'KMH_MASSM_BY_PU'),
       ('ppType', 'kmhMassmByPu.ppType', 'тип поточного ПП', TRUE, 'KMH_MASSM_BY_PU'),
       ('ppNumber', 'kmhMassmByPu.ppNumber', 'заводской номер поточного ПП', TRUE, 'KMH_MASSM_BY_PU'),
       ('ppDate', 'kmhMassmByPu.ppDate', 'дата поверки поточного ПП', TRUE, 'KMH_MASSM_BY_PU'),


-- Таблица 1
       ('V_KP_0', 'kmhMassmByPu.' || 'V_KP_0',
        'вместимость калиброванного участка компакт-прувера согласно свидетельству о поверке',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('delta_KP', 'kmhMassmByPu.' || 'delta_KP',
        'пределы относительной погрешности компакт-прувера согласно описани. Типа (или из свидетельства о поверке), %',
        TRUE, 'KMH_MASSM_BY_PU'),

       ('D', 'kmhMassmByPu.' || 'D',
        'внутренний диаметр калиброванного участка компакт-прувера (значение берут из паспорта или эксплуатационной документации на компакт-прувер), мм',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('E', 'kmhMassmByPu.' || 'E',
        'модуль упругости материала стенок компакт-прувера (значение берут из таблицы Б.1 приложения Б), Мпа', TRUE,
        'KMH_MASSM_BY_PU'),

       ('s', 'kmhMassmByPu.' || 's',
        'толщина стенок калиброванного участка компакт-прувера (значение берут из паспорта или эксплуатационной документации на компакт-прувер), мм',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('delta_t_KP', 'kmhMassmByPu.' || 'delta_t_KP',
        'пределы допускаемых абсолюьных погрешностей датчика температуры (или термометров), используемых в процессе поверки для измерений температуры рабочей жидкости в компакт-прувере,  ºC (из действующих свидетельств о поверке)',
        TRUE, 'KMH_MASSM_BY_PU'),

       ('delta_PP', 'kmhMassmByPu.' || 'delta_PP',
        'пределы допускаемой относительной погрешности поточного ПП, применяемого при поверке массомера, % (из свидетельства о поверке)',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('delta_t_PP', 'kmhMassmByPu.' || 'delta_t_PP',
        'пределы допускаемых абсолюьных погрешностей датчика температуры (или термометров), используемых в процессе поверки для измерений температуры рабочей жидкости в поточном ПП,  ºC (из действующих свидетельств о поверке)',
        TRUE, 'KMH_MASSM_BY_PU'),

       ('delta_UOI_K', 'kmhMassmByPu.' || 'delta_UOI_K',
        'пределы допускаемой относительной погрешности УОИ при вычислении К-фактора массомера, % (из описания типа или свидетельства о поверке)',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('KF_conf', 'kmhMassmByPu.' || 'KF_conf',
        '', TRUE, 'KMH_MASSM_BY_PU'),
       ('ZS', 'kmhMassmByPu.' || 'ZS',
        'значение стабильности нуля, т/ч (из описания типа массомера)', TRUE, 'KMH_MASSM_BY_PU'),
       ('alpha_cyl_t', 'kmhMassmByPu.' || 'alpha_cyl_t',
        '', TRUE, 'KMH_MASSM_BY_PU'),
       ('alpha_cyl_t_sq', 'kmhMassmByPu.' || 'alpha_cyl_t_sq',
        '', TRUE, 'KMH_MASSM_BY_PU'),
       ('alpha_st_t', 'kmhMassmByPu.' || 'alpha_st_t',
        '', TRUE, 'KMH_MASSM_BY_PU'),

       -- Таблица 2
       ('Q_TPR_ij', 'kmhMassmByPu.' || 'Q_TPR_ij',
        'Расход для вычисления коэффициента ТПР',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('N_TPR_ij_avg', 'kmhMassmByPu.' || 'N_TPR_ij_avg',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('t_TPR_ij_avg', 'kmhMassmByPu.' || 't_TPR_ij_avg',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('P_TPR_ij_avg', 'kmhMassmByPu.' || 'P_TPR_ij_avg',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('t_KP_ij_avg', 'kmhMassmByPu.' || 't_KP_ij_avg',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('P_KP_ij_avg', 'kmhMassmByPu.' || 'P_KP_ij_avg',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('t_st_ij', 'kmhMassmByPu.' || 't_st_ij',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),

-- Заданная масса
       ('mass', 'kmhMassmByPu.' || 'mass',
        'Заданная масса, т',
        TRUE, 'KMH_MASSM_BY_PU'),

       -- Таблица 3
       ('Q_ij', 'kmhMassmByPu.' || 'Q_ij',
        'Расход для определения МХ массомера',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('t_il', 'kmhMassmByPu.' || 't_il',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('P_il', 'kmhMassmByPu.' || 'P_il',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('t_TPR', 'kmhMassmByPu.' || 't_TPR',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('P_TPR', 'kmhMassmByPu.' || 'P_TPR',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('rho_TPR', 'kmhMassmByPu.' || 'rho_TPR',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('M_il', 'kmhMassmByPu.' || 'M_il',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('M_TPR', 'kmhMassmByPu.' || 'M_TPR',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('delta_M', 'kmhMassmByPu.' || 'delta_M',
        '',
        TRUE, 'KMH_MASSM_BY_PU'),

       -- Нижняя часть
       ('deliver_name', 'kmhMassmByPu.' || 'deliver_name',
        'Фамилия И.О. лица от сдающей стороны',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('receiver_org', 'kmhMassmByPu.' || 'receiver_org',
        'Организация принимающей стороны',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('receiver_name', 'kmhMassmByPu.' || 'receiver_name',
        'Фамилия И.О. лица от принимающей стороны',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('service_org', 'kmhMassmByPu.' || 'service_org',
        'Название сервисной организации',
        TRUE, 'KMH_MASSM_BY_PU'),
       ('service_name', 'kmhMassmByPu.' || 'service_name',
        'Фамилия И.О. лица от сервисной организации',
        TRUE, 'KMH_MASSM_BY_PU');

-- выходные данные
INSERT INTO tag (permanent_name, address, description, initial, report_type)
VALUES ('V_KP_pr_ij', 'kmhMassmByPu.' || 'V_KP_pr_ij',
        'вместимость калиброванного участка',
        FALSE, 'KMH_MASSM_BY_PU'),
       ('K_TPR_ij', 'kmhMassmByPu.' || 'K_TPR_ij',
        'коэффициент преобразования ТПР для каждой i-ой серии проходов поршня в j-ой точке расхода, имп/м3',
        FALSE, 'KMH_MASSM_BY_PU'),
       ('Pi_j', 'kmhMassmByPu.' || 'Pi_j',
        'повторяемость коэффициентов преобразования ТПР, %',
        FALSE, 'KMH_MASSM_BY_PU'),
       ('K_TPR_j', 'kmhMassmByPu.' || 'K_TPR_j',
        'коэффициент преобразования ТПР в j-ой точке расхода, имп/м3',
        FALSE, 'KMH_MASSM_BY_PU'),
       ('delta_max', 'kmhMassmByPu.' || 'delta_max',
        '',
        FALSE, 'KMH_MASSM_BY_PU'),
       ('conclusion', 'kmhMassmByPu.' || 'conclusion',
        'годен/не годен',
        FALSE, 'KMH_MASSM_BY_PU');